import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { readFileSync, writeFileSync, existsSync, unlinkSync } from 'fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

/**
 * After each build, merge the CSS emitted by esbuild (main.css) into styles.css
 * so that Obsidian picks it up via the standard plugin CSS mechanism.
 */
function mergeCssPlugin() {
	return {
		name: 'merge-css',
		setup(build) {
			build.onEnd(() => {
				if (existsSync('main.css')) {
					const generatedCss = readFileSync('main.css', 'utf-8');
					// Preserve any hand-authored styles that live BELOW the generated block
					const marker = '/* === generated by esbuild === */';
					let existing = existsSync('styles.css') ? readFileSync('styles.css', 'utf-8') : '';
					// Strip previously generated block so we don't accumulate duplicates
					const markerIdx = existing.indexOf(marker);
					if (markerIdx !== -1) {
						existing = existing.slice(0, markerIdx).trimEnd();
					}
					const output = (existing ? existing + '\n\n' : '') + marker + '\n' + generatedCss;
					writeFileSync('styles.css', output);
					unlinkSync('main.css');
				}
			});
		}
	};
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	loader: {
		// Inline any font files Monaco references as data URIs
		'.ttf': 'dataurl',
	},
	plugins: [mergeCssPlugin()],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
