import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { readFileSync, writeFileSync, existsSync, unlinkSync, cpSync, mkdirSync, rmSync } from 'fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

/**
 * After each build, merge the CSS emitted by esbuild (main.css) into styles.css
 * so that Obsidian picks it up via the standard plugin CSS mechanism.
 */
function mergeCssPlugin() {
	return {
		name: 'merge-css',
		setup(build) {
			build.onEnd(() => {
				if (existsSync('main.css')) {
					const generatedCss = readFileSync('main.css', 'utf-8');
					// Preserve any hand-authored styles that live BELOW the generated block
					const marker = '/* === generated by esbuild === */';
					let existing = existsSync('styles.css') ? readFileSync('styles.css', 'utf-8') : '';
					// Strip previously generated block so we don't accumulate duplicates
					const markerIdx = existing.indexOf(marker);
					if (markerIdx !== -1) {
						existing = existing.slice(0, markerIdx).trimEnd();
					}
					const output = (existing ? existing + '\n\n' : '') + marker + '\n' + generatedCss;
					writeFileSync('styles.css', output);
					unlinkSync('main.css');
				}
			});
		}
	};
}

function copyNodePtyRuntime() {
	const sourceRoot = 'node_modules/node-pty';
	const targetRoot = 'vendor/node-pty';

	rmSync(targetRoot, { recursive: true, force: true });
	mkdirSync(targetRoot, { recursive: true });

	const libSourcePath = `${sourceRoot}/lib`;
	if (existsSync(libSourcePath)) {
		cpSync(libSourcePath, `${targetRoot}/lib`, {
			recursive: true,
			filter: sourcePath =>
				!sourcePath.endsWith('.map') &&
				!sourcePath.endsWith('.test.js'),
		});
	}

	const releaseSourcePath = `${sourceRoot}/build/Release`;
	if (existsSync(releaseSourcePath)) {
		cpSync(releaseSourcePath, `${targetRoot}/build/Release`, {
			recursive: true,
		});
	}

	const prebuildsSourcePath = `${sourceRoot}/prebuilds`;
	if (existsSync(prebuildsSourcePath)) {
		cpSync(prebuildsSourcePath, `${targetRoot}/prebuilds`, {
			recursive: true,
		});
	}

	const windowsPtyAgentPath = `${targetRoot}/lib/windowsPtyAgent.js`;
	if (existsSync(windowsPtyAgentPath)) {
		const windowsPtyAgentSource = readFileSync(windowsPtyAgentPath, 'utf-8');
		const patchedSnippet = [
			'        if (this._useConpty) {',
			'            // The conout socket must be ready out on another thread to avoid deadlocks',
			'            this._conoutSocketWorker = new windowsConoutConnection_1.ConoutConnection(term.conout, this._useConptyDll);',
			'            this._conoutSocketWorker.onReady(function () {',
			'                _this._conoutSocketWorker.connectSocket(_this._outSocket);',
			'            });',
			'        }',
			'        else {',
			'            this._outSocket.connect(term.conout);',
			'        }',
			"        this._outSocket.on('connect', function () {",
			"            _this._outSocket.emit('ready_datapipe');",
			'        });',
		].join('\n');
		const originalSnippetPattern =
			/        \/\/ The conout socket must be ready out on another thread to avoid deadlocks\r?\n        this\._conoutSocketWorker = new windowsConoutConnection_1\.ConoutConnection\(term\.conout, this\._useConptyDll\);\r?\n        this\._conoutSocketWorker\.onReady\(function \(\) \{\r?\n            _this\._conoutSocketWorker\.connectSocket\(_this\._outSocket\);\r?\n        \}\);\r?\n        this\._outSocket\.on\('connect', function \(\) \{\r?\n            _this\._outSocket\.emit\('ready_datapipe'\);\r?\n        \}\);/;

		writeFileSync(
			windowsPtyAgentPath,
			windowsPtyAgentSource.replace(originalSnippetPattern, patchedSnippet),
		);
	}
}

function copyTerminalRuntimePlugin() {
	return {
		name: 'copy-terminal-runtime',
		setup(build) {
			build.onEnd(() => {
				copyNodePtyRuntime();
			});
		}
	};
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	loader: {
		// Inline any font files Monaco references as data URIs
		'.ttf': 'dataurl',
	},
	plugins: [mergeCssPlugin(), copyTerminalRuntimePlugin()],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
